### ISSUE TITLE
placeholder mixin not working?

### ISSUE THREAD

**Issue by morenoh149** [krkn/kouto-swiss#38]
Hello I'm working on a site. Here we use the placeholder mixin https://github.com/r3dm/shpe-sfba/blob/master/stylus/footer.styl#L49 But the placeholder css being produced doesn't reflect what I want https://github.com/r3dm/shpe-sfba/blob/master/public/styles/style.css#L6770 it always seems to assign color `#999` and I can't make it italic.
Is it a problem with my setup?

**Comment by leny** [comment]
Hi,

I'm currently busy changing all my hardware so I can't clone your stuffs to view it by the details, but when I look at your stylesheet, it seems that you're loading **kouto-swiss** _and_ **bootstrap**. It's possible that the `placeholder` mixin is overrided by bootstrap.

Try by using `ks-placeholder` instead of `placeholder`.

**Comment by morenoh149** [comment]
that was is it! this is excellent!
